* How I got started in public speaking
** Theater
I'll admit it, to a certain extent I had it easier than a lot of other people.
When I was in high school I did theatre, which meant that right off the bat I
was already doing some amount of standing in front of people and presenting. I
knew that it was something I liked, and I had gotten good at giving
presentations. So much so, that in college I presented instead of a final exam.
To one extent I felt good at it, but really I had a lot of practice and had
enough things that I could refer to. Not that anyone asks, but I take great
pride in the fact that for the first play I was ever cast in, I was in the
background selling fish, and when I finished high school I won best actor at my
high school theater.
* Oscon
When my high school friends talk about me, not a single one of them describes me
as a gambler. Yet that's totally what I felt like when I decided to pursue a
career in an area completely different from what I had studied for years. My
degree is in linguistics. For some reason, I decided to get into software
engineering.

I was lucky to end up going to a Java user group, a meetup. There again I got
lucky by winning a ticket to the Open Source Conference, one of the biggest in
our industry. So very early on I was exposed to lots of smart people sharing
their knowledge for the good of the community.
* Jordan
In the fall of 2013, I moved to Washington DC and began my career as a software
engineer. There (at another meetup) I met Jordan Kasper. He was working at
Strongloop, the company that was currently one of the biggest in the Node.js.

His whole job was speaking at conferences. And now what he wanted to do was
encourage more diversity in our industry by helping new people get started in
speaking. He's an awesome guy, seriously.

Jordan told me what it was like for him to get started. He helped me brainstorm
ideas for new talks. Then, he guided me through the process of turning those
thoughts into well-structured conference talk proposal, the first of which was
accepted to JSConf Uruguay in the spring of 2016.
* speaking repo, and awesome-conference-proposals
Knowing already that I would want to also help build up others to encourage even
more diversity of thought in our industry, I started taking lots of notes.
Eventually I serialized those notes into a github repo,
[JuanCaicedo/speaking](https://github.com/JuanCaicedo/awesome-conference-proposals).
My goal is to always shared my talks so that they can serve as an example for
others wanting to get into the industry.

As I met other speakers in the industry, I found out that some of them had done
this as well. That lead me to create
[awesome-conference-proposals](https://github.com/JuanCaicedo/awesome-conference-proposals)
a project where I want to showcase submissions from successful speakers from all
different backgrounds
* Global Diversity CFP day
Do you want to get into public speaking? If so, I really recommend the [Global
Diversity CFP day](https://www.globaldiversitycfpday.com/). Volunteers will
walk you through the whole process, just like Jordan did for me.

We have one going on [in Medellín](https://www.globaldiversitycfpday.com/events/126)! If you find yourself in the area, please come 😀
